In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
iris = datasets.load_iris()
iris_X =iris.data
iris_y = iris.target

In [4]:
iris_X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
iris_y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=0.2)

In [7]:
y_train

array([[5.4, 3.9, 1.3, 0.4],
       [6.3, 2.7, 4.9, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3. , 5.1, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [5.1, 3.3, 1.7, 0.5],
       [6.1, 2.9, 4.7, 1.4],
       [6.8, 3.2, 5.9, 2.3],
       [5.7, 2.6, 3.5, 1. ],
       [6.4, 3.2, 4.5, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.8, 3. , 1.4, 0.3],
       [6. , 3. , 4.8, 1.8],
       [4.8, 3.4, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [6.6, 3. , 4.4, 1.4],
       [5.6, 3. , 4.1, 1.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5.8, 2.7, 5.1, 1.9],
       [4.7, 3.2, 1.3, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [5.1, 3.8, 1.5, 0.3],
       [5.2, 4.1, 1.5, 0.1],
       [4.3, 3. , 1.1, 0.1]])

In [8]:
len(y_train)

30

In [9]:
len(iris_y)

150

In [16]:
y_train.shape

(120,)

In [17]:
X_train.shape

(120, 4)

In [18]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print(knn.predict(X_test))
print(y_test)

[2 1 1 0 1 1 2 1 0 2 2 2 2 2 2 1 2 2 1 1 2 1 1 0 1 2 1 0 2 2]
[2 1 1 0 1 1 2 1 0 2 2 2 2 2 2 1 2 2 1 1 2 1 1 0 1 2 1 0 2 2]


AttributeError: 'numpy.ndarray' object has no attribute 'isnull'